[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = --strict-markers --tb=short
markers =
    unit: unit tests
    integration: integration tests
    slow: slow tests
